-- ID, 이름, 주소, 냉동시설 여부 조회 (냉동시설 여부가 null이면 'N') ID기준 오름차순

SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N')
FROM FOOD_WAREHOUSE
WHERE SUBSTR(ADDRESS,1,3) = "경기도"
ORDER BY WAREHOUSE_ID